const ROLES = Object.freeze({USER: 'USER', ADMIN: 'ADMIN'});
const AUTHOR_STATUS = Object.freeze({NONE: 'NONE', PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', SUSPENDED: 'SUSPENDED'});
const ACCOUNT_STATUS = Object.freeze({ACTIVE: 'ACTIVE', SUSPENDED: 'SUSPENDED', DEACTIVATED: 'DEACTIVATED'});
const STORY_STATUS = Object.freeze({DRAFT: 'DRAFT', ONGOING: 'ONGOING', COMPLETED: 'COMPLETED', PAUSED: 'PAUSED'});
const STORY_VISIBILITY = Object.freeze({PUBLIC: 'PUBLIC', PRIVATE: 'PRIVATE', UNLISTED: 'UNLISTED'});
const CHAPTER_STATUS = Object.freeze({DRAFT: 'DRAFT', PENDING_REVIEW: 'PENDING_REVIEW', APPROVED: 'APPROVED', PUBLISHED: 'PUBLISHED', REJECTED: 'REJECTED', REVISION_REQUIRED: 'REVISION_REQUIRED', HIDDEN: 'HIDDEN'});
const CONTENT_REVIEW_STATUS = Object.freeze({DRAFT: 'DRAFT', PENDING_REVIEW: 'PENDING_REVIEW', APPROVED: 'APPROVED', REJECTED: 'REJECTED', REVISION_REQUIRED: 'REVISION_REQUIRED', ARCHIVED: 'ARCHIVED'});

module.exports = {ROLES, AUTHOR_STATUS, ACCOUNT_STATUS, STORY_STATUS, STORY_VISIBILITY, CHAPTER_STATUS, CONTENT_REVIEW_STATUS};
