const {AppError} = require('../../utils/AppError');
const {getContentRepositories} = require('../../repositories/contentRuntime');
const {ROLES, CHAPTER_STATUS} = require('../../constants/roles');
function sameId(a, b) { return String(a) === String(b); }
function owner(story, user) { if (!story || !user) throw new AppError('Story not found', 404, 'NOT_FOUND'); if (user.role !== ROLES.ADMIN && !sameId(story.creatorId, user.id)) throw new AppError('You do not own this story', 403, 'FORBIDDEN'); }
function chapterSlug(title, number) { const base = String(title).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'chapter'; return `${number}-${base}`; }
async function create(storyId, data, user) { const repos = getContentRepositories(); const story = await repos.story.findById(storyId); owner(story, user); if (!data.chapterNumber || !data.title) throw new AppError('Chapter number and title are required', 422, 'VALIDATION_ERROR'); if (data.status === 'HIDDEN') throw new AppError('Unsupported legacy chapter status', 422, 'UNMAPPABLE_LEGACY_STATUS'); if (await repos.chapter.findByStoryAndNumber(story.id, Number(data.chapterNumber))) throw new AppError('Chapter number already exists', 409, 'CONFLICT'); let chapter; try { chapter = await repos.chapter.createChapter({storyId: story.id, creatorId: story.creatorId, chapterNumber: Number(data.chapterNumber), title: data.title, slug: data.slug || chapterSlug(data.title, data.chapterNumber), content: data.content || '', status: data.status || CHAPTER_STATUS.DRAFT}); await repos.story.incrementChapterCount(story.id); return chapter; } catch (error) { if (chapter) { try { await repos.chapter.softDelete(chapter.id, user.id); } catch {} } if (error.code === 'CHAPTER_NUMBER_EXISTS') throw new AppError('Chapter number already exists', 409, 'CONFLICT'); throw error; } }
async function list(storyId, user) { const repos = getContentRepositories(); const story = await repos.story.findById(storyId); if (!story) throw new AppError('Story not found', 404, 'NOT_FOUND'); const manager = user && (user.role === ROLES.ADMIN || sameId(story.creatorId, user.id)); if (manager) return repos.chapter.findByStory(story.id); if (story.visibility !== 'PUBLIC' || story.reviewStatus !== 'APPROVED') throw new AppError('Story not found', 404, 'NOT_FOUND'); return repos.chapter.findPublicByStory(story.id); }
async function getById(id, user) { const repos = getContentRepositories(); const chapter = await repos.chapter.findById(id); if (!chapter) throw new AppError('Chapter not found', 404, 'NOT_FOUND'); const story = await repos.story.findById(chapter.storyId); const manager = user && story && (user.role === ROLES.ADMIN || sameId(story.creatorId, user.id)); if (manager) return chapter; if (chapter.status === 'APPROVED' && story?.visibility === 'PUBLIC' && story.reviewStatus === 'APPROVED') return chapter; throw new AppError('Chapter not found', 404, 'NOT_FOUND'); }
async function update(id, data, user) { const repos = getContentRepositories(); const chapter = await repos.chapter.findById(id); if (!chapter) throw new AppError('Chapter not found', 404, 'NOT_FOUND'); const story = await repos.story.findById(chapter.storyId); owner(story, user); if (data.status === 'HIDDEN') throw new AppError('Unsupported legacy chapter status', 422, 'UNMAPPABLE_LEGACY_STATUS'); if (data.chapterNumber && (await repos.chapter.findByStoryAndNumber(story.id, Number(data.chapterNumber)))?.id !== chapter.id) throw new AppError('Chapter number already exists', 409, 'CONFLICT'); try { return await repos.chapter.updateEditable(id, data); } catch (error) { if (error.code === 'CHAPTER_NUMBER_EXISTS') throw new AppError('Chapter number already exists', 409, 'CONFLICT'); throw error; } }
async function remove(id, user) { const repos = getContentRepositories(); const chapter = await repos.chapter.findById(id); if (!chapter) throw new AppError('Chapter not found', 404, 'NOT_FOUND'); const story = await repos.story.findById(chapter.storyId); owner(story, user); await repos.chapter.softDelete(id, user.id); try { await repos.story.incrementChapterCount(story.id, -1); } catch (error) { if (repos.chapter.restore) { try { await repos.chapter.restore(chapter.id); } catch {} } throw error; } return chapter; }
async function publish(id, user) { const repos = getContentRepositories(); const chapter = await repos.chapter.findById(id); if (!chapter) throw new AppError('Chapter not found', 404, 'NOT_FOUND'); owner(await repos.story.findById(chapter.storyId), user); return repos.chapter.submitForModeration(id); }
async function moderate(id, status, user) { if (user.role !== ROLES.ADMIN) throw new AppError('Admin permission is required', 403, 'FORBIDDEN'); const chapter = await getContentRepositories().chapter.findById(id); if (!chapter) throw new AppError('Chapter not found', 404, 'NOT_FOUND'); if (![CHAPTER_STATUS.APPROVED, CHAPTER_STATUS.REJECTED, CHAPTER_STATUS.REVISION_REQUIRED].includes(status)) throw new AppError('Invalid chapter moderation status', 422, 'VALIDATION_ERROR'); return getContentRepositories().chapter.reviewModeration(id, {status, reviewedBy: user.id, reviewedAt: new Date(), moderationNote: '', publishedAt: status === CHAPTER_STATUS.APPROVED ? new Date() : null}); }
module.exports = {create, list, getById, update, remove, publish, moderate};
