const {ROLES, AUTHOR_STATUS, ACCOUNT_STATUS, STORY_VISIBILITY} = require('../constants/roles');

// Planning-only shapes. The official Mongoose registrations are User.js,
// OtpToken.js, and AuthorApplication.js. This file creates no models and has
// no runtime side effects; AUDIOTALENTS_DATABASE_CORE_V1.md remains canonical.
const userSchema = {username: 'string', email: 'string', passwordHash: 'private string', role: Object.values(ROLES), authorStatus: Object.values(AUTHOR_STATUS), accountStatus: Object.values(ACCOUNT_STATUS), emailVerified: 'boolean', tokenVersion: 'number', profile: '{bio:string,avatar:string|null}', lastLoginAt: 'datetime|null', createdAt: 'datetime', updatedAt: 'datetime'};
const otpTokenSchema = {userId: 'user id', email: 'string', codeHash: 'private string', purpose: 'EMAIL_VERIFICATION|PASSWORD_RESET', expiresAt: 'datetime', attempts: 'number', maxAttempts: 'number', usedAt: 'datetime|null', invalidatedAt: 'datetime|null', createdAt: 'datetime', updatedAt: 'datetime'};
const authorApplicationSchema = {userId: 'user id', displayName: 'string', bio: 'string', contentTypes: 'string[]', experience: 'string', status: 'PENDING|APPROVED|REJECTED|CANCELLED', submittedAt: 'datetime', reviewedAt: 'datetime|null', reviewedBy: 'user id|null', reviewNote: 'string', createdAt: 'datetime', updatedAt: 'datetime'};
const genreSchema = {name: 'string', slug: 'string', description: 'string', icon: 'string|null', isActive: 'boolean', sortOrder: 'number', createdAt: 'datetime', updatedAt: 'datetime'};
const tagSchema = {name: 'string', normalizedName: 'string', slug: 'string', isActive: 'boolean', createdAt: 'datetime', updatedAt: 'datetime'};
const taxonomyProposalSchema = {type: 'GENRE|TAG', proposedName: 'string', normalizedName: 'string', reason: 'string', proposerId: 'user id', storyId: 'story id', status: 'PENDING|APPROVED|REJECTED', reviewedBy: 'user id|null', reviewedAt: 'datetime|null', reviewNote: 'string', resolvedTaxonomyId: 'object id|null', createdAt: 'datetime', updatedAt: 'datetime'};
const storySchema = {creatorId: 'user id', title: 'string', slug: 'string', description: 'string', coverUrl: 'string|null', genreIds: 'genre id[]', tags: 'string[]', status: 'ONGOING|COMPLETED|PAUSED', reviewStatus: 'DRAFT|PENDING_REVIEW|APPROVED|REJECTED|REVISION_REQUIRED', visibility: Object.values(STORY_VISIBILITY), chapterCount: 'number', viewCount: 'number', listenCount: 'number', favoriteCount: 'number', ratingAverage: 'number', ratingCount: 'number', submittedAt: 'datetime|null', reviewedBy: 'user id|null', reviewedAt: 'datetime|null', moderationNote: 'string', publishedAt: 'datetime|null', deletedAt: 'datetime|null', deletedBy: 'user id|null', createdAt: 'datetime', updatedAt: 'datetime'};
const chapterSchema = {storyId: 'story id', creatorId: 'user id', chapterNumber: 'number>=1', title: 'string', slug: 'string', textContent: 'string', status: 'DRAFT|PENDING_REVIEW|APPROVED|REJECTED|REVISION_REQUIRED', submittedAt: 'datetime|null', reviewedBy: 'user id|null', reviewedAt: 'datetime|null', moderationNote: 'string', publishedAt: 'datetime|null', deletedAt: 'datetime|null', deletedBy: 'user id|null', createdAt: 'datetime', updatedAt: 'datetime'};
const audioSchema = {storyId: 'story id', chapterId: 'chapter id', creatorId: 'user id', title: 'string', partNumber: 'positive integer, unique within chapter', audioUrl: 'string', storageKey: 'string|null', durationSec: 'number|null>=0', fileSize: 'number|null>=0', mimeType: 'string|null', bitrate: 'number|null>=0', voiceType: 'string|null', transcript: "UTF-8 JSON string of TranscriptSegment[] (default '')", sourceType: 'HUMAN|AI|HYBRID', processingStatus: 'PENDING|PROCESSING|READY|FAILED', status: 'DRAFT|PENDING_REVIEW|APPROVED|REJECTED|REVISION_REQUIRED', isPrimary: 'boolean', deletedAt: 'datetime|null', deletedBy: 'user id|null', createdAt: 'datetime', updatedAt: 'datetime'};
const libraryItemSchema = {userId: 'user id', storyId: 'story id', isFavorite: 'boolean', followed: 'boolean', addedAt: 'datetime', createdAt: 'datetime', updatedAt: 'datetime'};
const listenHistorySchema = {userId: 'user id', storyId: 'story id', chapterId: 'chapter id', audioId: 'audio id', positionSec: 'number>=0', durationSec: 'number|null>=0', progressPercent: 'number:0..100', completed: 'boolean', lastListenedAt: 'datetime', createdAt: 'datetime', updatedAt: 'datetime'};
const playlistSchema = {userId: 'user id', name: 'string', description: 'string', storyIds: 'unique story id[]', visibility: 'PRIVATE|PUBLIC', createdAt: 'datetime', updatedAt: 'datetime'};
const notificationSchema = {userId: 'user id', type: 'canonical notification type', title: 'string', message: 'string', targetType: 'STORY|CHAPTER|AUDIO|AUTHOR_APPLICATION|SYSTEM', targetId: 'object id|null', isRead: 'boolean', readAt: 'datetime|null', createdAt: 'datetime', updatedAt: 'datetime'};
const commentSchema = {userId: 'user id', storyId: 'story id', chapterId: 'chapter id|null', parentCommentId: 'comment id|null', content: 'string', status: 'ACTIVE|HIDDEN|DELETED', likeCount: 'number>=0', createdAt: 'datetime', updatedAt: 'datetime'};
const ratingSchema = {userId: 'user id', storyId: 'story id', stars: 'integer:1..5', review: 'string|null', createdAt: 'datetime', updatedAt: 'datetime'};
const reportSchema = {reporterId: 'user id', targetType: 'STORY|CHAPTER|AUDIO|COMMENT|USER', targetId: 'object id', reportType: 'canonical report type', description: 'string', status: 'OPEN|REVIEWING|RESOLVED|REJECTED', reviewedBy: 'user id|null', reviewedAt: 'datetime|null', resolutionNote: 'string|null', createdAt: 'datetime', updatedAt: 'datetime'};
const auditLogSchema = {actorId: 'user id', action: 'string', targetType: 'flexible string', targetId: 'object id', metadata: 'mixed object', ipAddress: 'string|null', userAgent: 'string|null', createdAt: 'datetime'};

module.exports = {
  userSchema, otpTokenSchema, authorApplicationSchema, genreSchema, tagSchema, taxonomyProposalSchema, storySchema, chapterSchema, audioSchema,
  libraryItemSchema, listenHistorySchema, playlistSchema,
  notificationSchema, commentSchema, ratingSchema, reportSchema,
  auditLogSchema,
};
