const {AppError} = require('../../utils/AppError');
const {getContentRepositories} = require('../../repositories/contentRuntime');
const {STORY_VISIBILITY, ROLES} = require('../../constants/roles');
function sameId(left, right) { return String(left) === String(right); }
function assertOwner(story, user) { if (!story) throw new AppError('Story not found', 404, 'NOT_FOUND'); if (user.role !== ROLES.ADMIN && !sameId(story.creatorId, user.id)) throw new AppError('You do not own this story', 403, 'FORBIDDEN'); }
function validateStory(data) { const errors = []; if (!data.title || data.title.trim().length < 2) errors.push('title'); if (!data.description) errors.push('description'); if (!Array.isArray(data.genres)) errors.push('genres'); return errors; }
async function buildUniqueSlug(title) { const base = title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'story'; let slug = base; let suffix = 2; while (await getContentRepositories().story.findBySlug(slug, {includeDeleted: true})) slug = `${base}-${suffix++}`; return slug; }
async function resolveGenreIds(genres, repositories) {
  if (repositories.runtime !== 'MONGO') return genres;
  const resolved = [];
  for (const genre of genres) {
    const value = String(genre);
    const record = await repositories.genre.findById(value).catch(() => null) || await repositories.genre.findBySlug(value);
    if (!record || record.isActive === false) throw new AppError('Genre is not active', 422, 'VALIDATION_ERROR');
    resolved.push(record.id);
  }
  return [...new Set(resolved)];
}
async function resolveTagNames(tags, repositories) { if (repositories.runtime !== 'MONGO') return tags || []; const active = await repositories.tag.listActive(); const resolved = []; for (const value of tags || []) { const normalized = String(value).trim().replace(/\s+/g, ' ').toLowerCase(); const record = active.find(item => String(item.normalizedName || item.name).toLowerCase() === normalized || String(item.slug).toLowerCase() === normalized); if (!record) throw new AppError('Tag is not active', 422, 'VALIDATION_ERROR'); resolved.push(record.name); } return [...new Set(resolved)]; }
async function create(data, user) { if (user.role !== ROLES.ADMIN && user.authorStatus !== 'APPROVED') throw new AppError('Approved author permission is required', 403, 'FORBIDDEN'); const errors = validateStory(data); if (errors.length) throw new AppError('Story validation failed', 422, 'VALIDATION_ERROR', {fields: errors}); const repositories = getContentRepositories(); const slug = await buildUniqueSlug(data.title); try { return await repositories.story.createStory({title: data.title.trim(), slug, description: data.description, cover: data.cover || null, creatorId: user.id, genres: await resolveGenreIds(data.genres, repositories), tags: await resolveTagNames(data.tags, repositories), reviewStatus: 'DRAFT', visibility: STORY_VISIBILITY.PRIVATE}); } catch (error) { if (error.code === 'STORY_SLUG_EXISTS') throw new AppError('Story already exists', 409, 'CONFLICT'); throw error; } }
async function getById(id, user) { const story = await getContentRepositories().story.findById(id); if (!story) throw new AppError('Story not found', 404, 'NOT_FOUND'); if (user && (user.role === ROLES.ADMIN || sameId(story.creatorId, user.id))) return story; if (story.visibility === 'PUBLIC' && story.reviewStatus === 'APPROVED') return story; throw new AppError('Story not found', 404, 'NOT_FOUND'); }
async function listByOwner(user) { return getContentRepositories().story.findByCreator(user.id); }
async function getBySlug(slug, user) { const story = await getContentRepositories().story.findBySlug(slug); if (!story) throw new AppError('Story not found', 404, 'NOT_FOUND'); if (story.visibility === 'PUBLIC' && story.reviewStatus === 'APPROVED') return story; if (user && (user.role === ROLES.ADMIN || sameId(story.creatorId, user.id))) return story; throw new AppError('Story not found', 404, 'NOT_FOUND'); }
async function list(query, user) { const repositories = getContentRepositories(); let genreId = query.genre || undefined; if (genreId && repositories.runtime === 'MONGO') { const genre = await repositories.genre.findById(String(genreId)).catch(() => null) || await repositories.genre.findBySlug(String(genreId)); if (!genre) return []; genreId = genre.id; } const publicResult = query.search ? await repositories.story.searchPublic(query.search, {page: 1, limit: 100, genreId, sort: query.sort}) : await repositories.story.listPublic({page: 1, limit: 100, genreId, sort: query.sort}); let stories = publicResult.items; if (user) { const mine = await repositories.story.findByCreator(user.id); stories = [...stories, ...mine.filter(item => !stories.some(publicItem => publicItem.id === item.id))]; } if (query.status) stories = stories.filter(item => item.status === query.status || item.reviewStatus === query.status); return stories; }
async function update(id, data, user) { const repositories = getContentRepositories(); const story = await repositories.story.findById(id); assertOwner(story, user); const changes = {...data}; for (const key of ['creatorId', 'rating', 'views', 'listens', 'reviewStatus', 'reviewedBy', 'reviewedAt', 'publishedAt', 'deletedAt', 'deletedBy', 'chapterCount', 'viewCount', 'listenCount', 'favoriteCount', 'ratingAverage', 'ratingCount']) delete changes[key]; if (changes.genres !== undefined) changes.genres = await resolveGenreIds(changes.genres, repositories); if (changes.tags !== undefined) changes.tags = await resolveTagNames(changes.tags, repositories); const updated = await repositories.story.updateEditable(id, changes); return story.reviewStatus === 'APPROVED' ? repositories.story.submitForModeration(id) : updated; }
async function remove(id, user) { const story = await getContentRepositories().story.findById(id); assertOwner(story, user); await getContentRepositories().story.softDelete(id, user.id); return story; }
async function hasPendingGenreProposal(storyId, repositories) { if (!repositories.proposal) return false; const rows = await repositories.proposal.list({storyId, type: 'GENRE', status: 'PENDING'}).catch(() => []); return rows.some(row => row.type === 'GENRE' && row.status === 'PENDING'); }
async function hasCanonicalGenre(story) { return (story.genreIds || story.genres || []).length > 0; }
async function submit(id, user) { const repositories = getContentRepositories(); const story = await repositories.story.findById(id); assertOwner(story, user); if (!story.title || !story.description || (!(await hasCanonicalGenre(story)) && !(await hasPendingGenreProposal(story.id, repositories)))) throw new AppError('Story is not ready for review', 422, 'VALIDATION_ERROR'); return repositories.story.submitForModeration(id); }
async function moderate(id, status, user) { if (user.role !== ROLES.ADMIN) throw new AppError('Admin permission is required', 403, 'FORBIDDEN'); const repositories = getContentRepositories(); const story = await repositories.story.findById(id); if (!story) throw new AppError('Story not found', 404, 'NOT_FOUND'); if (!['APPROVED','REJECTED','REVISION_REQUIRED'].includes(status)) throw new AppError('Invalid moderation status', 422, 'VALIDATION_ERROR'); if (status === 'APPROVED' && repositories.proposal && !(await hasCanonicalGenre(story))) throw new AppError('Story requires a canonical Genre before approval', 422, 'TAXONOMY_REQUIRED'); return repositories.story.reviewModeration(id, {reviewStatus: status, reviewedBy: user.id, reviewedAt: new Date(), moderationNote: '', publishedAt: status === 'APPROVED' ? new Date() : null, visibility: status === 'APPROVED' ? STORY_VISIBILITY.PUBLIC : STORY_VISIBILITY.PRIVATE}); }
module.exports = {create, getById, getBySlug, list, listByOwner, update, remove, submit, moderate, assertOwner, buildUniqueSlug};
