const express = require('express');
const {authMiddleware, optionalAuth, requireAuthorOrAdmin} = require('../../middleware/auth');
const {roleMiddleware} = require('../../middleware/roles');
const {asyncHandler} = require('../../middleware/asyncHandler');
const {ROLES} = require('../../constants/roles');
const controller = require('./storyController');
const router = express.Router();
router.get('/author/stories', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.listMine));
router.get('/author/stories/:id', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.getById));
router.post('/author/stories', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.create));
router.patch('/author/stories/:id', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.update));
router.delete('/author/stories/:id', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.remove));
router.post('/author/stories/:id/submit', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.submit));
router.get('/', optionalAuth, asyncHandler(controller.list));
router.get('/trending', optionalAuth, asyncHandler(controller.list));
router.get('/new', optionalAuth, asyncHandler(controller.list));
router.get('/top-rated', optionalAuth, asyncHandler(controller.list));
router.get('/completed', optionalAuth, asyncHandler(controller.list));
router.get('/recommended', optionalAuth, asyncHandler(controller.list));
router.get('/id/:id', optionalAuth, asyncHandler(controller.getById));
router.get('/:slug', optionalAuth, asyncHandler(controller.getBySlug));
router.post('/', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.create));
router.patch('/:id', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.update));
router.delete('/:id', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.remove));
router.post('/:id/submit', authMiddleware, roleMiddleware(ROLES.USER, ROLES.ADMIN), requireAuthorOrAdmin, asyncHandler(controller.submit));
router.patch('/:id/moderate', authMiddleware, roleMiddleware(ROLES.ADMIN), asyncHandler(controller.moderate));
module.exports = router;
