const {AppError} = require('../../utils/AppError');
const {getContentRepositories} = require('../../repositories/contentRuntime');
async function list() { return getContentRepositories().genre.listActive(); }
async function getBySlug(slug) { const genre = await getContentRepositories().genre.findBySlug(slug); if (!genre) throw new AppError('Genre not found', 404, 'NOT_FOUND'); return genre; }
const normalizeName = value => String(value || '').trim().replace(/\s+/g, ' ').toLowerCase();
async function create(data) { if (!data.name || !data.slug) throw new AppError('Name and slug are required', 422, 'VALIDATION_ERROR'); const repositories = getContentRepositories(); const existing = repositories.genre.listAll ? await repositories.genre.listAll() : []; if (existing.some(item => normalizeName(item.name) === normalizeName(data.name) || String(item.slug).toLowerCase() === String(data.slug).trim().toLowerCase())) throw new AppError('Genre already exists', 409, 'CONFLICT'); try { return await repositories.genre.createGenre({name: data.name, slug: data.slug, description: data.description || '', icon: data.icon ?? null, isActive: true}); } catch (error) { if (error.code === 'GENRE_SLUG_EXISTS') throw new AppError('Genre already exists', 409, 'CONFLICT'); throw error; } }
async function update(id, data) { const repositories = getContentRepositories(); const current = await repositories.genre.findById(id); if (!current) throw new AppError('Genre not found', 404, 'NOT_FOUND'); const all = repositories.genre.listAll ? await repositories.genre.listAll() : []; if (all.some(item => item.id !== current.id && (normalizeName(item.name) === normalizeName(data.name || current.name) || String(item.slug).toLowerCase() === String(data.slug || current.slug).trim().toLowerCase()))) throw new AppError('Genre already exists', 409, 'CONFLICT'); try { return await repositories.genre.updateGenre(id, data); } catch (error) { if (error.code === 'GENRE_SLUG_EXISTS') throw new AppError('Genre already exists', 409, 'CONFLICT'); throw error; } }
async function setActive(id, isActive) { const genre = await getContentRepositories().genre.findById(id); if (!genre) throw new AppError('Genre not found', 404, 'NOT_FOUND'); return getContentRepositories().genre.setActive(id, isActive); }
async function listAll() { return getContentRepositories().genre.listAll(); }
module.exports = {list, listAll, getBySlug, create, update, setActive};
